### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by miguelgondu** [LeoIV/bounce#2]
Hi @LeoIV,

Thanks for making the source code for `bounce` available. I'm a fan of the structure of your code, it has been super easy to extend.

I'm currently running a comparison against other methods for high-dimensional BO. I was wondering: is the code provided under any license in particular?

**Comment by lpapenme** [comment]
Hi @miguelgondu, 

I tried to make the code easy to read and extend; I'm glad you liked it! I added an MIT license.
